#!/usr/bin/env python3
"""Generate and optionally submit PBS job scripts for Census RDC servers.

Default: prints the PBS script to stdout so you can inspect it.
Add --submit to actually write the script and run qsub.

Usage:
    # See what a production ML job looks like
    python -m screening.rdc.submit ml_prod --cmd "python my_gbt.py"

    # Submit it for real
    python -m screening.rdc.submit ml_prod --cmd "python my_gbt.py" --submit

    # Interactive debugging session (just prints the qsub command to paste)
    python -m screening.rdc.submit interactive

    # Auto-estimate memory for 150M rows
    python -m screening.rdc.submit ml_prod --cmd "python gbt.py" --data-rows 150000000

    # Custom resources
    python -m screening.rdc.submit custom --ncpus 16 --mem 128gb --walltime 72:00:00 \\
        --cmd "python big_job.py"

Profiles:
    debug        2 CPU,   8 GB,  2h   — interactive debugging
    dev          4 CPU,  32 GB, 12h   — development batch runs
    ml_prod      8 CPU,  64 GB, 48h   — production ML (GBT on 150M obs)
    est_prod     8 CPU,  64 GB, 48h   — production estimation (100M params)
    interactive  (prints qsub -I command, no script)
    custom       (you specify everything via --ncpus, --mem, --walltime)
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Profiles — just dicts. No classes, no registry, no indirection.
# ---------------------------------------------------------------------------

PROFILES = {
    "debug": {
        "ncpus": 2,
        "mem": "8gb",
        "walltime": "02:00:00",
        "desc": "Small interactive debugging",
    },
    "dev": {
        "ncpus": 4,
        "mem": "32gb",
        "walltime": "12:00:00",
        "desc": "Medium batch development run",
    },
    "ml_prod": {
        "ncpus": 8,
        "mem": "64gb",
        "walltime": "48:00:00",
        "desc": "Large batch production ML (GBT on 150M obs)",
    },
    "est_prod": {
        "ncpus": 8,
        "mem": "64gb",
        "walltime": "48:00:00",
        "desc": "Large batch production estimation (100M params)",
    },
    "custom": {
        "ncpus": 1,
        "mem": "5gb",
        "walltime": "04:00:00",
        "desc": "Custom — override with --ncpus, --mem, --walltime",
    },
}


# ---------------------------------------------------------------------------
# PBS script generation — one big f-string, heavily commented
# ---------------------------------------------------------------------------


def generate_pbs_script(
    cmd: str,
    ncpus: int,
    mem: str,
    walltime: str,
    name: str,
    logdir: str,
    profile: str,
    data_dir: str | None = None,
    output_dir: str | None = None,
) -> str:
    """Generate a self-contained PBS bash script as a string.

    Every generated script includes diagnostic echo blocks so that when
    something fails in a batch job at 3 AM, the log file tells you the
    hostname, job ID, Python version, and working directory.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Build env var exports
    env_exports = []
    env_exports.append('export PYTHONPATH="."')
    env_exports.append('export OMP_NUM_THREADS=1')
    env_exports.append('export OPENBLAS_NUM_THREADS=1')
    env_exports.append('export MKL_NUM_THREADS=1')
    env_exports.append('export NUMEXPR_NUM_THREADS=1')
    env_exports.append('export XLA_FLAGS="--xla_cpu_multi_thread_eigen=false"')
    if data_dir:
        env_exports.append(f'export SCREENING_DATA_DIR="{data_dir}"')
    if output_dir:
        env_exports.append(f'export SCREENING_OUTPUT_DIR="{output_dir}"')
    env_block = "\n".join(env_exports)

    profile_desc = PROFILES.get(profile, {}).get("desc", "custom")

    script = f"""#!/bin/bash
#PBS -N {name}
#PBS -l select=1:ncpus={ncpus}:mem={mem}
#PBS -l walltime={walltime}
#PBS -o {logdir}
#PBS -e {logdir}
#PBS -j oe

# ------------------------------------------------------------------
# Generated by screening.rdc.submit on {timestamp}
# Profile: {profile} ({profile_desc})
# Resources: {ncpus} CPUs, {mem} memory, {walltime} walltime
# Command: {cmd}
# ------------------------------------------------------------------

# ---- Environment setup ----
cd "$PBS_O_WORKDIR" 2>/dev/null || cd .
{env_block}

# ---- Diagnostics (printed to log for debugging) ----
echo "==========================================="
echo "JOB START"
echo "==========================================="
echo "Date:        $(date)"
echo "Hostname:    $(hostname)"
echo "Job ID:      ${{PBS_JOBID:-interactive}}"
echo "Working dir: $(pwd)"
echo "Python:      $(python --version 2>&1)"
echo "PYTHONPATH:  $PYTHONPATH"
echo "SCREENING_DATA_DIR:   ${{SCREENING_DATA_DIR:-not set}}"
echo "SCREENING_OUTPUT_DIR: ${{SCREENING_OUTPUT_DIR:-not set}}"
echo "==========================================="

# ---- Run the command ----
{cmd}
EXIT_CODE=$?

# ---- Summary ----
echo "==========================================="
echo "JOB END"
echo "Date:      $(date)"
echo "Exit code: $EXIT_CODE"
if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "JOB FAILED. Common causes:"
    echo "  Exit 1:   Python error — check traceback above"
    echo "  Exit 137: Killed (out of memory) — request more with --mem"
    echo "  Exit 134: Abort (segfault) — check numpy/scipy version"
fi
echo "==========================================="
exit $EXIT_CODE
"""
    return script


# ---------------------------------------------------------------------------
# Interactive mode — just prints what to type
# ---------------------------------------------------------------------------


def print_interactive_help(ncpus: int, mem: str) -> None:
    """Print the qsub command for an interactive session."""
    print("To start an interactive PBS session, paste this command:\n")
    print(f"    qsub -I -X -l select=1:ncpus={ncpus}:mem={mem}\n")
    print("Then inside the session:")
    print("    cd /projects/<project_id>/programs")
    print("    export PYTHONPATH=.")
    print("    python rdc/env_check.py          # check environment")
    print("    python                            # interactive Python")
    print("    stata-se                          # interactive Stata")
    print("    sas                               # interactive SAS")
    print()
    print("Interactive sessions timeout after 10-12 hours.")
    print("For long runs, use a batch profile instead (debug, dev, ml_prod, est_prod).")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate PBS job scripts for Census RDC servers.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Profiles:
  debug        2 CPU,   8 GB,  2h    interactive debugging
  dev          4 CPU,  32 GB, 12h    development batch runs
  ml_prod      8 CPU,  64 GB, 48h    production ML (GBT on 150M obs)
  est_prod     8 CPU,  64 GB, 48h    production estimation (100M params)
  interactive  (prints qsub -I command to paste)
  custom       (specify --ncpus, --mem, --walltime)

Examples:
  python -m screening.rdc.submit ml_prod --cmd "python my_gbt.py"
  python -m screening.rdc.submit interactive
  python -m screening.rdc.submit dev --cmd "python test.py" --submit
""",
    )
    parser.add_argument("profile", choices=list(PROFILES.keys()) + ["interactive"],
                        help="Resource profile to use")
    parser.add_argument("--cmd", type=str, default=None,
                        help="Python command to run (required for batch profiles)")
    parser.add_argument("--ncpus", type=int, default=None,
                        help="Override CPU count")
    parser.add_argument("--mem", type=str, default=None,
                        help="Override memory (e.g. '48gb')")
    parser.add_argument("--walltime", type=str, default=None,
                        help="Override walltime (e.g. '24:00:00')")
    parser.add_argument("--name", type=str, default=None,
                        help="PBS job name (default: auto from profile)")
    parser.add_argument("--logdir", type=str, default="./logs",
                        help="PBS log output directory")
    parser.add_argument("--data-dir", type=str, default=None,
                        help="Set SCREENING_DATA_DIR in the job")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Set SCREENING_OUTPUT_DIR in the job")
    parser.add_argument("--submit", action="store_true",
                        help="Actually write script and submit via qsub (default: print only)")
    parser.add_argument("--data-rows", type=int, default=None,
                        help="Number of data rows (triggers memory auto-estimate)")
    parser.add_argument("--data-cols", type=int, default=10,
                        help="Number of data columns for memory estimate")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Interactive mode: just print help and exit
    if args.profile == "interactive":
        ncpus = args.ncpus or 2
        mem = args.mem or "8gb"
        print_interactive_help(ncpus, mem)
        return

    # Resolve profile defaults + overrides
    profile = PROFILES[args.profile]
    ncpus = args.ncpus or profile["ncpus"]
    mem = args.mem or profile["mem"]
    walltime = args.walltime or profile["walltime"]
    name = args.name or f"rdc_{args.profile}"

    # Memory auto-estimate if --data-rows given
    if args.data_rows:
        workload = "ml" if "ml" in args.profile else "estimation"
        try:
            from screening.rdc.helpers import estimate_pbs_memory
            estimated = estimate_pbs_memory(args.data_rows, args.data_cols, workload)
            if not args.mem:
                mem = estimated
                print(f"Using auto-estimated memory: {mem}\n")
        except ImportError:
            # helpers not importable — estimate inline
            raw_gb = args.data_rows * args.data_cols * 8 / 1e9
            mult = 3.0 if "ml" in args.profile else 2.0
            import math
            total = int(math.ceil((raw_gb * mult + 4) / 8)) * 8
            mem = f"{total}gb"
            print(f"Estimated memory: {mem} (raw {raw_gb:.1f} GB x {mult:.0f} + 4 GB overhead)\n")

    # Require --cmd for batch profiles
    if not args.cmd:
        print("ERROR: --cmd is required for batch profiles.")
        print("Example: python -m screening.rdc.submit ml_prod --cmd 'python my_script.py'")
        sys.exit(1)

    # Ensure logdir exists (or will exist)
    Path(args.logdir).mkdir(parents=True, exist_ok=True)

    # Generate the script
    script = generate_pbs_script(
        cmd=args.cmd,
        ncpus=ncpus,
        mem=mem,
        walltime=walltime,
        name=name,
        logdir=args.logdir,
        profile=args.profile,
        data_dir=args.data_dir,
        output_dir=args.output_dir,
    )

    if args.submit:
        # Write to temp file and submit
        script_path = Path(args.logdir) / f"{name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.bash"
        script_path.write_text(script)
        print(f"Script written to: {script_path}")
        print(f"Submitting via qsub...")

        result = subprocess.run(["qsub", str(script_path)], capture_output=True, text=True)
        if result.returncode == 0:
            job_id = result.stdout.strip()
            print(f"Submitted! Job ID: {job_id}")
            print(f"Check status: qstat {job_id}")
            print(f"Kill job:     qdel {job_id}")
            print(f"Logs will be in: {args.logdir}")
        else:
            print(f"qsub failed (exit {result.returncode})")
            print(f"stderr: {result.stderr.strip()}")
            print(f"\nScript saved at: {script_path}")
            print(f"You can inspect it and submit manually: qsub {script_path}")
    else:
        # Print-only mode (default)
        print("# ---- Generated PBS Script (not submitted) ----")
        print("# To submit: add --submit flag, or save and run qsub manually")
        print("#")
        print(script)
        print("# ---- End of script ----")
        print(f"# To submit: python -m screening.rdc.submit {args.profile} "
              f"--cmd '{args.cmd}' --submit")


if __name__ == "__main__":
    main()
